### ISSUE TITLE
0 volume/weight crafting recipe

### ISSUE THREAD

**Issue by Ignaramico** [foulman/Psioniclysm#1]
# Describe the bug

if you start crafting the recipe for the psi upgrade, the ongoing craft has a 0 weight/volume, so if you stop and carry it and then place it somewhere else, it shows the debug message of the item having a weight/volume of 0

# Steps To Reproduce
1. start crafting any of the psi upgrades
2. stop the ongoing craft
3. put it in inventory
4. move it from the advanced inventory menu

# Screenshots

![image](https://user-images.githubusercontent.com/34730575/83465660-402d7200-a43a-11ea-8f6b-99790635d245.png)

**Comment by foulman** [comment]
I had a weight and volume on the output objects, but my guess is that weight of in-progress items are determined by the input, I had no input objects. At least for now I have made that a rock, presumably you play with it using PK. I dunno. It now has weight/volume and won't do any funky mess.

**Comment by Ignaramico** [comment]
Yeah, that solved the problem, thanks a lot n.n/
