### ISSUE TITLE
Infinite PK Hold 1

### ISSUE THREAD

**Issue by Ignaramico** [foulman/Psioniclysm#6]
PK Hold 1 doesnt require more than me staring at my enemies to keep them in place.

![image](https://user-images.githubusercontent.com/34730575/83709915-254b3100-a5e5-11ea-8ffd-d2224dcb2985.png)

**Comment by foulman** [comment]
lol. *facepalm*  
cut and paste mistake I guess, there's no mana cost set. I'll fix it right away.
